 [[plugins]]
 repo = 'itchyny/lightline.vim'
 [[plugins]]
 repo = 'Shougo/vimshell.vim'
 [[plugins]]
 repo = 'Shougo/unite.vim'
 [[plugins]]
 repo = 'cohama/lexima.vim'
 [[plugins]]
 repo = 'munshkr/vim-tidal'
 [[plugins]]
 repo = 'octol/vim-cpp-enhanced-highlight'
 [[plugins]]
 repo = 'altercation/vim-colors-solarized'
 [[plugins]]
 repo = 'tpope/vim-surround'
 [[plugins]]
 repo = 'scrooloose/nerdtree'
 [[plugins]]
 repo = 'mattn/sonictemplate-vim'
 [[plugins]]
 repo = 'tpope/vim-fugitive'
 [[plugins]]
 repo = 'tomtom/tcomment_vim'
 [[plugins]]
 repo = 'vim-airline/vim-airline'
 [[plugins]]
 repo = 'vim-airline/vim-airline-themes'
 [[plugins]]
 repo = 'dense-analysis/ale'
 [[plugins]]
 repo = 'junegunn/fzf.vim'
 [[plugins]]
 repo = 'Chiel92/vim-autoformat'
 [[plugins]]
 repo = 'wordijp/NeoDebug'
