[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = '''
if !exists("g:quickrun_config")
  let g:quickrun_config={}
endif
augroup rust_quickrun
autocmd BufNewFile,BufRead *.crs setf rust
autocmd BufNewFile,BufRead *.rs  let g:quickrun_config.rust = {'exec' : 'cargo run'}
autocmd BufNewFile,BufRead *.crs let g:quickrun_config.rust = {'exec' : 'cargo script %s -- %a'}
augroup END
'''

[[plugins]]
repo = 'iamcco/markdown-preview.nvim'
on_ft = ['markdown', 'pandoc.markdown', 'rmd']
build = 'sh -c "cd app && yarn install"'

[[plugins]]
repo = 'itchyny/calendar.vim'

[[plugins]]
repo = 'mattn/emmet-vim'

[[plugins]]
repo = 'cohama/lexima.vim'
on_event = 'InsertEnter'

[[plugins]]
repo = 'mattn/sonictemplate-vim'
hook_add = '''
let g:sonictemplate_vim_template_dir = ['$HOME/template']
nnoremap <Space>y :e $HOME/template/cpp<CR>
nnoremap <Space>t :Template<Space>
'''

[[plugins]]
repo='skanehira/denops-docker.vim'
depends_on=['denops.vim']
