[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = '''
if !exists("g:quickrun_config")
  let g:quickrun_config={}
endif
augroup rust_quickrun
autocmd BufNewFile,BufRead *.crs setf rust
autocmd BufNewFile,BufRead *.rs  let g:quickrun_config.rust = {'exec' : 'cargo run'}
autocmd BufNewFile,BufRead *.crs let g:quickrun_config.rust = {'exec' : 'cargo script %s -- %a'}
augroup END
'''

[[plugins]]
repo = 'iamcco/markdown-preview.nvim'
on_ft = ['markdown', 'pandoc.markdown', 'rmd', 'plantuml']
build = 'sh -c "cd app && yarn install"'
hook_add = '''
let g:mkdp_filetypes = ['markdown', 'plantuml']
'''

[[plugins]]
repo = 'itchyny/calendar.vim'

[[plugins]]
repo = 'mattn/emmet-vim'

[[plugins]]
repo = 'cohama/lexima.vim'
on_event = 'InsertEnter'

[[plugins]]
repo = 'mattn/sonictemplate-vim'
hook_add = '''
let g:sonictemplate_vim_template_dir = ['$HOME/template']
nnoremap <Space>y :e $HOME/template/cpp<CR>
'''

[[plugins]]
repo='skanehira/denops-docker.vim'
depends=['denops.vim']

[[plugins]]
repo = 'plasticboy/vim-markdown'
hook_add = '''
let g:vim_markdown_math = 1
let g:vim_markdown_folding_disabled = 1
let g:vim_markdown_new_list_item_indent = 0
'''

[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
merged = 0
on_event = 'BufRead'
hook_post_update = 'TSUpdate'
hook_source = '''
lua <<EOF
require('nvim-treesitter.configs').setup {
  ensure_installed = "all",
  highlight = {
    enable = true,
  },
}
EOF
'''

