name: mac

on:
  push:
    branches:
      - master

jobs:
  test-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup shell
        run: ./setup_shell.sh
        shell: zsh {0}
      - name: setup.sh
        run: CI=1 ./setup.sh
        shell: zsh {0}
      - name: setup_vim.sh
        run: ./setup_vim.sh
        shell: zsh {0}
